service: sls-sqs-test

custom:
  # Definimos variaveis de ambiente aqui também
  settings:
    ACCOUNT_ID: '811678370367'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment: ${self:custom.settings}
  # BEGIN: Adicionar permissão para fila que queremos enviar
  
  # END: Adicionar permissão para fila que queremos enviar

functions:
  hello:
    handler: handler.hello
    role: LambdaRole
    events:
      - http:
          method: get
          path: hello
  # BEGIN: Lambda que é chamado pela fila
  sqsHello:
    handler: handler.sqsHello
    role: LambdaRole
    events: 
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 1
  # END: Lambda que é chamado pela fila

resources:
  Resources:
    # BEGIN SQS
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
    # END SQS
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: 'slsSqsTest'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: slsSqsTest-service-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'sqs:sendMessage'
                    - 'sqs:deleteMessage'
                    - 'sqs:getQueueAttributes'
                    - 'sqs:receiveMessage'
                  Resource: 'arn:aws:sqs:${self:provider.region}:*:MyQueue'


# Imprimir logs serverless logs -f nomeLambda -t